#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sorhy?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dkzkepal1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 20MB

logging.level:
  com.amazonaws.util:
    EC2MetadataUtils: error
  org.hibernate.SQL: debug
  org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: evan-image-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIARWPFIVZYMNEKHZW2
      secret-key: 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

jwt:
  secret: akjldfadlksjflkflkasndf!@$!@$slakdfklasdnfasi;ofnsad;ifasndf;lsdfknfdslkf