INSERT INTO company (COMPANY_NAME, COMPANY_SCORE) VALUES ('직방', 0);
INSERT INTO company (COMPANY_NAME, COMPANY_SCORE) VALUES ('삼성전자', 0);
INSERT INTO company (COMPANY_NAME, COMPANY_SCORE) VALUES ('삼성전기', 0);
INSERT INTO company (COMPANY_NAME, COMPANY_SCORE) VALUES ('삼성생명', 0);
INSERT INTO company (COMPANY_NAME, COMPANY_SCORE) VALUES ('삼성화재', 0);
INSERT INTO company (COMPANY_NAME, COMPANY_SCORE) VALUES ('싸피', 0);
