INSERT INTO company (COMPANY_ID, COMPANY_NAME, COMPANY_SCORE) VALUES (0, "싸피", 0);
INSERT INTO company (COMPANY_ID, COMPANY_NAME, COMPANY_SCORE) VALUES (0, "삼성전자", 0);
INSERT INTO company (COMPANY_ID, COMPANY_NAME, COMPANY_SCORE) VALUES (0, "삼성전기", 0);
INSERT INTO company (COMPANY_ID, COMPANY_NAME, COMPANY_SCORE) VALUES (0, "삼성생명", 0);
INSERT INTO company (COMPANY_ID, COMPANY_NAME, COMPANY_SCORE) VALUES (0, "삼성화재", 0);
INSERT INTO company (COMPANY_ID, COMPANY_NAME, COMPANY_SCORE) VALUES (0, "직방", 0);